name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:         
      - name: Check out code    
        uses: actions/checkout@v3
      
      - name: Kind Cluster
        uses: helm/kind-action@v1.5.0
        
      - name: "install kuttl"
      - run: sudo curl -Lo /usr/local/bin/kubectl-kuttl https://github.com/kudobuilder/kuttl/releases/download/v0.12.1/kubectl-kuttl_0.12.1_linux_x86_64,
      - run: sudo chmod +x /usr/local/bin/kubectl-kuttl
      - run: export PATH=$PATH:/usr/local/bin
     
      - name: "Run tests"     
      - run: kubectl kuttl test --start-kind=true  ./tests/e2e/  
