name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:         
      - name: Check out code    
        uses: actions/checkout@v3
      
      - name: Kind Cluster
        uses: helm/kind-action@v1.5.0
        
      - name: "install kuttl"
        run: ./installKuttl.sh
     
      - name: "Run tests"     
        run: kubectl kuttl test --start-kind=true  ./tests/e2e/  
